### ISSUE TITLE
Password Credentials - Client ID

### ISSUE THREAD

**Issue by stephenheron** [commerceguys/guzzle-oauth2-plugin#17]
Hi Guys,

I am using the PasswordCredentials grant type and I think I noticed a problem. 

On line 19 of the [PasswordCredentials GrantType](https://github.com/commerceguys/guzzle-oauth2-plugin/blob/master/src/GrantType/PasswordCredentials.php#L19) it merges the parents required parameters with the username,password. 

The parents [getRequired](https://github.com/commerceguys/guzzle-oauth2-plugin/blob/master/src/GrantType/GrantTypeBase.php#L47) returns 'client_id'.

This means that the PasswordCredentials required parameters become ['client_id', 'username', 'password']. I don't however think this is correct as looking at the [RFC](http://tools.ietf.org/html/rfc6749#section-4.3.1) it states that only grant_type, username and password are the required parameters. 

I have only started using the plugin so I might be doing things wrong but I wanted to flag it anyway.

Thanks,
Stephen

**Comment by bojanz** [comment]
That is correct. From the RFC you linked:

> The authorization server MUST:
>
>   require client authentication for confidential clients or for any
>      client that was issued client credentials (or with other
>      authentication requirements),

So, each flow requires a client_id unless you allow every client (which I've never heard anyone do).

**Comment by stephenheron** [comment]
Hi Bojan,

Thanks for getting back to me so quickly! 

The RFC shows this as a example for getting an access token: 

>POST /token HTTP/1.1
>Host: server.example.com
>Authorization: Basic czZCaGRSa3F0MzpnWDFmQmF0M2JW
>Content-Type: application/x-www-form-urlencoded
>grant_type=password&username=johndoe&password=A3ddj3w

It does not contain the client_id. I thought the section that you quoted was discussing the requirement for Basic Auth but I may be wrong.

Thanks,
Stephen

**Comment by pjcdawkins** [comment]
Hi Stephen

The client ID in that is czZCaGRSa3F0MzpnWDFmQmF0M2JW

**Comment by pjcdawkins** [comment]
Client credentials can be sent in the body as 'client_id' and 'client_secret', or in Basic authentication - see https://github.com/commerceguys/guzzle-oauth2-plugin/pull/16

**Comment by stephenheron** [comment]
Hi Patrick,

Ah right ok I see now! Thanks for clearing that up. 

Do you know when your pull request will be merged in?

Thanks,
Stephen

**Comment by pjcdawkins** [comment]
Done! I'll tag a release with that soon (I want to review the other PR first) - if that all makes sense then please close this issue

**Comment by stephenheron** [comment]
Fantastic! 

Thanks everyone this is maybe the best interaction I have ever on GitHub. 

Keep up the good work ;) 

Thanks,
Stephen

**Comment by stephenheron** [comment]
Hi Guys,

Sorry for reopening the issue but I might have noticed another wee issue. 

In change that was made to add the client_id/client_secret to the headers: [GrantTypeBase.php Line 70](https://github.com/commerceguys/guzzle-oauth2-plugin/blob/master/src/GrantType/GrantTypeBase.php#L70). The client_id and client_secret are being unset from the $body but on line 66 the body has already been assigned to the $requestOptions array. Meaning that the unset on line 70 has no effect.

Thanks,
Stephen

**Comment by pjcdawkins** [comment]
Correct... I'll fix that...!

**Comment by pjcdawkins** [comment]
Thanks
