### ISSUE TITLE
Get error: Invalid version string "^2.0"

### ISSUE THREAD

**Issue by mike-potter** [commerceguys/guzzle-oauth2-plugin#20]
Trying to use this plugin.  My composer.json file is:
{
    "require": {
        "commerceguys/guzzle-oauth2-plugin": "~2.0"
    }
}

when I do a "drush composer install" I get the error:

[RuntimeException]
  Could not load package commerceguys/guzzle-oauth2-plugin in http://packagist.org: [UnexpectedValueException] Could not parse version constraint ^2.0: Invalid version string "^2.0"

My composer version is:
Composer version 1.0-dev (b2173d28fc8b56236eddc8aa10dcda61471633ec) 2015-06-16 10:43:55

The issue seems to be that guzzle-oauth2-plugin has a dependency:
   "firebase/php-jwt": "^2.0"

and it doesn't seem to like the ^ character.  Any ideas?

**Comment by mike-potter** [comment]
Btw, this was using "drush composer".  Looks like maybe drush composer is using composer version 1.0.0-alpha9.  Not sure when the ^ syntax was added.

**Comment by mike-potter** [comment]
Discovered this issue: https://www.drupal.org/node/2461921

Looks like the drush composer needs to be updated.  Will run the self-update command and have posted to that issue queue to get it updated.

So not a problem with this oauth plugin, but hope this helps somebody else with trouble.

**Comment by pjcdawkins** [comment]
Thanks for the info! Yes, composer's `^` syntax was added in -alpha10, as far as I know. I'm using that Drush patch too for a separate problem.

But I'm not sure that we need to use the `^` for firebase/php-jwt, a `~` may be fine... @steffkes could answer that question.

**Comment by steffkes** [comment]
uhm, that's a good question @pjcdawkins - i'm pretty sure we can use another constraint as well, there is no specific reason to use _exactly_ that. this is the one that was auto generated using `composer require <package>`

i wasn't aware of composer changing constraint syntax, so i didn't look for something in the first place. should i check if there is something else?

**Comment by pjcdawkins** [comment]
Thanks, I've updated it with that commit. It's rare that people will be on old versions of Composer, but the difference is small, so this seems reasonable to me.

**Comment by steffkes** [comment]
LGTM! Thanks for the Fixes on `JwtBearer`!

**Comment by pjcdawkins** [comment]
By the way @mike-potter the Drush composer extension (version 8.x-1.2) now includes Composer alpha10.

http://cgit.drupalcode.org/composer
