### ISSUE TITLE
firebase/php-jwt dependency (2.2.0) breaks

### ISSUE THREAD

**Issue by kanariezwart** [commerceguys/guzzle-oauth2-plugin#21]
FYI:

firebase/php-jwt dependency is updated to version 2.2.0.
After a composer update deserialization no longer works, if I lock the firebase/php-jwt dependency to 2.1.0 all works as expected.

I will try to look for the issue myself.

**Comment by kanariezwart** [comment]
I couldn't find the actual problem but I think the bug is located when calling the 
GuzzleHttp\Message\Response through the subscribed guzzle client.

v 2.1.0:  ```php $response->getBody()->getContents(); // returns the content as string ```
v 2.2.0:  ```php $response->getBody()->getContents(); // returns empty string '' ```

When the response body is cast to string all works again.
```php 
(string)$response->getBody()
```
Got any ideas?

**Comment by pjcdawkins** [comment]
It probably means that the body has been read before somewhere. It's a *stream*:

```
$body = $response->getBody();

$body->getContents(); // string, on the first call
$body->getContents(); // empty string on subsequent calls

$body->seek(0);
$body->getContents(); // string again
```

**Comment by kanariezwart** [comment]
@pjcdawkins Should I try to rewind my getContents() before calling getContents()?
I don't think the body has been read before. Unless Guzzle (now) does some magic I'm still unaware of. I'll try to report back something useful asap.

**Comment by pjcdawkins** [comment]
Yes, rewind the body with `$body->seek(0)`, before getContents(), and see if that makes a difference

**Comment by kanariezwart** [comment]
Thanks will try. Updates folllow asap
