### ISSUE TITLE
Is this package still alive?

### ISSUE THREAD

**Issue by Aerendir** [commerceguys/guzzle-oauth2-plugin#28]

**Comment by kanariezwart** [comment]
:+1: I'm curious too

**Comment by chx** [comment]
:+1:

**Comment by dm** [comment]
This seems abandoned...
~~Using~~ Used this library at @Sainsburys (legacy that needed to be brought forward).

~~Maintaining~~ Maintained the fork at https://github.com/Sainsburys/guzzle-oauth2-plugin https://packagist.org/packages/sainsburys/guzzle-oauth2-plugin

Only **assured** backwards incompatibility change in minor versions ~~will be~~ were change of vendor name to `Sainsburys/`

**Update:** Please note I've left Sainsbury's, and the need to maintain that library was also deprecated; so I'm not sure it will be kept updated.

**Comment by bojanz** [comment]
It's dead, Jim.

**Comment by chx** [comment]
https://github.com/thephpleague/oauth2-client this seems to be the chosen one. It mostly works, it's severely underdocumented as all Oauth2 client libs are, have some interesting traps (like an object state change inside AbstractProvider::getAuthorizationParameters) but all in all, it can be made to work.
