### ISSUE TITLE
The getConfig Method from the Guzzle ClientInterface will be removed in 8

### ISSUE THREAD

**Issue by alexz707** [commerceguys/guzzle-oauth2-plugin#33]
Hi!
Do you already have some migrations plans for the getConfig method which will be removed in Guzzle 8?
It's already marked as deprecated and as far as I have followed the messages from the guzzle team there won't be an alternative to access the "real" config of the client..
Thanks & 
Regards Alex

**Comment by pjcdawkins** [comment]
This repo only works with Guzzle 5 ( #19 )

**Comment by alexz707** [comment]
Thanks for the info :)
