### ISSUE TITLE
Guzzle 4 support

### ISSUE THREAD

**Issue by ddeboer** [commerceguys/guzzle-oauth2-plugin#6]
I’ve opened a [PR at the Guzzle 4 repo for an OAuth2 subscriber](https://github.com/guzzle/oauth-subscriber/pull/3). As I took some ideas from your plugin, it would be useful if you guys had a look. If you want to be listed in the credits, please let me know.

**Comment by pjcdawkins** [comment]
I'm pretty sure the `guzzle5-support` branch of https://github.com/pjcdawkins/guzzle-oauth2-plugin is now working. Test with this in your `composer.json`:

```json
{
    "require": {
        "commerceguys/guzzle-5-oauth2-plugin": "dev-guzzle5-support"
    },
    "repositories": [
        {
            "type": "git",
            "url":  "https://github.com/pjcdawkins/guzzle-oauth2-plugin.git"
        }
    ]
}
```

**Comment by pjcdawkins** [comment]
The `master` branch is now for development on Guzzle 5. The `1.0` branch keeps Guzzle 3 support.

**Comment by chrisbarr** [comment]
Awesome, this is just what I needed! Any chance you could tag a new version so that I don't have to specify `dev-master` in my `composer.json`? Maybe a `2.0`?

**Comment by bojanz** [comment]
We could start with  a beta / RC at least.

**Comment by pjcdawkins** [comment]
Yes I could tag a `v2.0.0-beta1`, although it would have the same disadvantages for `composer.json` (you'd still need a stability flag)
