### ISSUE TITLE
PasswordCredentials expecting ClientInterface

### ISSUE THREAD

**Issue by arcovoltaico** [commerceguys/guzzle-oauth2-plugin#7]
Hi, I'm trying to run your plugin but an error stops me. Please help ;)

My code is:  
$url = 'http://httpbin.org/get';
 $oauth2Client = new Client(['base_url' => $url]);
 $config = array(
            'username' => 'myusername',
            'password' => 'mypassword',
            'client_id' => 'myclient',
            'client_secret' => 'mysecret',
            'scope' => 'administration', // Optional.
 );

 $grantType = new PasswordCredentials($oauth2Client, $config);

ERROR:
Catchable Fatal Error: Argument 1 passed to CommerceGuys\Guzzle\Plugin\Oauth2\GrantType\PasswordCredentials::__construct() must be an instance of Guzzle\Http\ClientInterface, instance of GuzzleHttp\Client given

composer.json requires:
        "guzzlehttp/guzzle": "*",
        "guzzlehttp/oauth-subscriber": "dev-master",
        "commerceguys/guzzle-oauth2-plugin": "dev-master"

**Comment by bojanz** [comment]
This was a Guzzle4/5 incompatibility (until recently the plugin only worked with Guzzle 3).
