### ISSUE TITLE
Config is missing refresh_token

### ISSUE THREAD

**Issue by misilot** [commerceguys/guzzle-oauth2-plugin#8]
Hi,

When I try using the example on the front page I am getting the following error:

```
 Config is missing the following keys: refresh_token
```

**Comment by pjcdawkins** [comment]
Ah yes, the example is wrong. The RefreshToken grant type should require a 'refresh_token' config key

**Comment by pjcdawkins** [comment]
... or maybe it shouldn't. Fixed with this commit https://github.com/commerceguys/guzzle-oauth2-plugin/commit/6936df59c183c04cd9a0ecc4bbc26101be4a62f3
